// <auto-generated/>
namespace Fanex.BetList.Core.UnitTest.Builder.OddsBuilder
{
    using Common;
    using Common.Enums;
    using Core.Builder.OddsBuilder;
    using Core.Templates;
    using Entities;
    using NUnit.Framework;
    using Stubs;

    public class Odds29Test
    {
        private Odds29 _odds;
        private ITicket _ticket;
        private ITicketHelper _ticketHelperStub;

        [SetUp]
        public void Setup()
        {
            _odds = new Odds29();
            _ticket = TestData.CreateTicket(BetTypes.Combine_Mix_Parlay);
            _ticketHelperStub = new TicketHelperStub();
        }

        [Test]
        public void StatusIsRunning_TemplateOddsIsHyphen()
        {
            // Arrange
            _ticket.Status = "running";

            // Act
            Odds_Template template = _odds.Render(_ticket, null, GetCachePropertyByIdStub);

            // Assert
            var expectedOdds = "-";
            Assert.AreEqual(expectedOdds, template.odds);
        }

        [Test]
        public void StatusIsNotRunning_TemplateOddsIsMasterOdds()
        {
            // Arrange
            _ticket.Status = "lose";

            // Act
            Odds_Template template = _odds.Render(_ticket, null, GetCachePropertyByIdStub);

            // Assert
            var expectedOdds = string.Format("<font color='#B50000'>{0}</font>", _ticket.MasterOdds);
            Assert.AreEqual(expectedOdds, template.odds);
        }

        [Test]
        public void OddsTypeIsNull_OddsTypeIsZero12()
        {
            // Arrange
            _ticket.OddsType = "1";

            // Act
            Odds_Template template = _odds.Render(_ticket, null, GetCachePropertyByIdStub);

            // Assert
            var expectedOdds = "1";
            Assert.AreEqual(expectedOdds, template.oddsType);
        }

        private string GetCachePropertyByIdStub(object id)
        {
            return id.ToString();
        }
    }
}