// <auto-generated/>
namespace Fanex.BetList.Core.UnitTest.Builder.OddsBuilder
{
    using Common;
    using Common.Enums;
    using Core.Builder.OddsBuilder;
    using Core.Templates;
    using Entities;
    using NUnit.Framework;
    using Stubs;

    public class Odds71Test
    {
        private Odds71 _odds;
        private ITicket _ticket;
        private ITicketHelper _ticketHelperStub;

        [SetUp]
        public void Setup()
        {
            _odds = new Odds71();
            _ticket = TestData.CreateTicket(BetTypes.Casino_Games);
            _ticketHelperStub = new TicketHelperStub();
        }

        [Test]
        public void Ticket_TemplateOddsIdHyphen()
        {
            // Act
            Odds_Template template = _odds.Render(_ticket, null, null);

            // Assert
            string expected = "-";
            Assert.AreEqual(expected, template.odds);
        }

        [Test]
        public void Ticket_TemplateOddsTypeIsEmpty()
        {
            // Act
            Odds_Template template = _odds.Render(_ticket, null, null);

            // Assert
            Assert.IsEmpty(template.oddsType);
        }
    }
}