// <auto-generated/>
namespace Fanex.BetList.Core.UnitTest.Utils.StringExt
{
    using Fanex.BetList.Core.Utils.StringExt;
    using NUnit.Framework;

    public class StringExtensionTest
    {
        [Test]
        public void UppercaseFirst_EmptyString_ReturnEmptyString()
        {
            // Arrange
            var value = string.Empty;

            // Act
            var result = StringExtension.UppercaseFirst(value);

            // Assert
            Assert.IsEmpty(result);
        }

        [Test]
        public void UppercaseFirst_ValidString_ReturnStringUpperTheFirstCharacter()
        {
            // Arrange
            var value = "sample";

            // Act
            var result = StringExtension.UppercaseFirst(value);

            // Assert
            var expected = "Sample";
            Assert.AreEqual(expected, result);
        }

        [Test]
        public void Count_ValidString_ReturnCountNumberOfSearchText()
        {
            // Arrange
            var value = "hello\nthe\nworld\n";
            var search = "\n";

            // Act
            var result = StringExtension.Count(value, search);

            // Assert
            var expected = 3;
            Assert.AreEqual(expected, result);
        }

        [Test]
        public void GetLineBreakTotal_ValidString_ReturnCountNumberOfLine()
        {
            // Arrange
            var value = "hello\nthe\nworld\n";

            // Act
            var result = StringExtension.GetLineBreakTotal(value);

            // Assert
            var expected = 4;
            Assert.AreEqual(expected, result);
        }
    }
}