// <auto-generated/>
// --------------------------------------------------------------------------
// <copyright file="BetTypes.cs" company="Nexcel Solutions Vietnam">
// Copyright (c) Nexcel Solutions Vietnam. All rights reserved.
// </copyright>
// --------------------------------------------------------------------------
// <history>
//   <change who="Edward.Nguyen" date="2014.5.30">Created</change>
// </history>

namespace Fanex.BetList.Core.UnitTest.Common.Enums
{
    /// <summary>
    /// Hard code bet types.
    /// </summary>
    public static class BetTypes
    {
        /// <summary>
        /// BetType = 0.
        /// </summary>
        public const int None = 0;

        /// <summary>
        /// BetType = 1.
        /// </summary>
        public const int Handicap = 1;

        /// <summary>
        /// BetType = 2.
        /// </summary>
        public const int Odd_Even = 2;

        /// <summary>
        /// BetType = 3.
        /// </summary>
        public const int Over_Under = 3;

        /// <summary>
        /// BetType = 4.
        /// </summary>
        public const int Correct_Score = 4;

        /// <summary>
        /// BetType = 5.
        /// </summary>
        public const int FT_1X2 = 5;

        /// <summary>
        /// BetType = 6.
        /// </summary>
        public const int Total_Goal = 6;

        /// <summary>
        /// BetType = 7.
        /// </summary>
        public const int _1st_Handicap = 7;

        /// <summary>
        /// BetType = 8.
        /// </summary>
        public const int _1st_Over_Under = 8;

        /// <summary>
        /// BetType = 9.
        /// </summary>
        public const int MixParlay = 9;

        /// <summary>
        /// BetType = 10.
        /// </summary>
        public const int Outright = 10;

        /// <summary>
        /// BetType = 11.
        /// </summary>
        public const int Total_Corners = 11;

        /// <summary>
        /// BetType = 12.
        /// </summary>
        public const int _1st_Odd_Even = 12;

        /// <summary>
        /// BetType = 13.
        /// </summary>
        public const int Clean_Sheet = 13;

        /// <summary>
        /// BetType = 14.
        /// </summary>
        public const int First_Goal_Last_Goal = 14;

        /// <summary>
        /// BetType = 15.
        /// </summary>
        public const int FirstHalf_1X2 = 15;

        /// <summary>
        /// BetType = 16.
        /// </summary>
        public const int HT_FT = 16;

        /// <summary>
        /// BetType = 17.
        /// </summary>
        public const int _2nd_HDP = 17;

        /// <summary>
        /// BetType = 18.
        /// </summary>
        public const int _2nd_Over_Under = 18;

        /// <summary>
        /// BetType = 19.
        /// </summary>
        public const int Substitutes = 19;

        /// <summary>
        /// BetType = 20.
        /// </summary>
        public const int Money_Line = 20;

        /// <summary>
        /// BetType = 21.
        /// </summary>
        public const int _1st_Money_Line = 21;

        /// <summary>
        /// BetType = 22.
        /// </summary>
        public const int Next_Goal = 22;

        /// <summary>
        /// BetType = 23.
        /// </summary>
        public const int Next_Corner = 23;

        /// <summary>
        /// BetType = 24.
        /// </summary>
        public const int Double_Change = 24;

        /// <summary>
        /// BetType = 25.
        /// </summary>
        public const int Draw_No_Bet = 25;

        /// <summary>
        /// BetType = 26.
        /// </summary>
        public const int Both_One_Neither = 26;

        /// <summary>
        /// BetType = 27.
        /// </summary>
        public const int To_Win_To_Nill = 27;

        /// <summary>
        /// BetType = 28.
        /// </summary>
        public const int _3_Way_Handicap = 28;

        /// <summary>
        /// BetType = 29.
        /// </summary>
        public const int Combine_Mix_Parlay = 29;

        /// <summary>
        /// BetType = 31.
        /// </summary>
        public const int Win = 31;

        /// <summary>
        /// BetType = 32.
        /// </summary>
        public const int Place = 32;

        /// <summary>
        /// BetType = 33.
        /// </summary>
        public const int Win_Place = 33;

        /// <summary>
        /// BetType = 41.
        /// </summary>
        public const int Win_UK_Tote = 41;

        /// <summary>
        /// BetType = 42.
        /// </summary>
        public const int Place_UK_Tote = 42;

        /// <summary>
        /// BetType = 43.
        /// </summary>
        public const int Win_Place_UK_Tote = 43;

        /// <summary>
        /// BetType = 51.
        /// </summary>
        public const int _5_min_O_U = 51;

        /// <summary>
        /// BetType = 52.
        /// </summary>
        public const int _15_min_O_U = 52;

        /// <summary>
        /// BetType = 53.
        /// </summary>
        public const int _30_min_O_U = 53;

        /// <summary>
        /// BetType = 54.
        /// </summary>
        public const int _45_min_O_U = 54;

        /// <summary>
        /// BetType = 55.
        /// </summary>
        public const int _60_min_O_U = 55;

        /// <summary>
        /// BetType = 56.
        /// </summary>
        public const int End_of_day_O_U = 56;

        /// <summary>
        /// BetType = 61.
        /// </summary>
        public const int _5_min_OE = 61;

        /// <summary>
        /// BetType = 62.
        /// </summary>
        public const int _15_min_OE = 62;

        /// <summary>
        /// BetType = 63.
        /// </summary>
        public const int _30_min_OE = 63;

        /// <summary>
        /// BetType = 64.
        /// </summary>
        public const int _45_min_OE = 64;

        /// <summary>
        /// BetType = 65.
        /// </summary>
        public const int _60_min_OE = 65;

        /// <summary>
        /// BetType = 66.
        /// </summary>
        public const int End_of_day_OE = 66;

        /// <summary>
        /// BetType = 71.
        /// </summary>
        public const int Casino_Games = 71;

        /// <summary>
        /// BetType = 72.
        /// </summary>
        public const int P2P_Games = 72;

        /// <summary>
        /// BetType = 73.
        /// </summary>
        public const int Bingo = 73;

        /// <summary>
        /// BetType = 121.
        /// </summary>
        public const int Home_No_Bet = 121;

        /// <summary>
        /// BetType = 122.
        /// </summary>
        public const int Away_No_Bet = 122;

        /// <summary>
        /// BetType = 123.
        /// </summary>
        public const int Draw_NoDraw = 123;

        /// <summary>
        /// BetType = 126.
        /// </summary>
        public const int _1h_Total_Goal = 126;

        /// <summary>
        /// BetType = 127.
        /// </summary>
        public const int _1h_First_Goal_Last_Goal = 127;

        /// <summary>
        /// BetType = 128.
        /// <para>
        /// Half Time/Full Time Odd/Even.
        /// </para>
        /// </summary>
        public const int HT_FT_OE = 128;

        /// <summary>
        /// BetType = 129.
        /// <para>
        /// First Halft Exact Goal
        /// </para>
        /// </summary>
        public const int FirstHalft_Exact_Goal = 129;

        /// <summary>
        /// BetType = 130.
        /// <para>
        /// Exact Goal
        /// </para>
        /// </summary>
        public const int Exact_Goal = 130;

        /// <summary>
        /// BetType = 131.
        /// <para>
        /// Home Team Total Goal
        /// </para>
        /// </summary>
        public const int Home_Team_Total_Goal = 131;

        /// <summary>
        /// BetType = 132.
        /// <para>
        /// Away Team Total Goal
        /// </para>
        /// </summary>
        public const int Away_Team_Total_Goal = 132;

        /// <summary>
        /// BetType = 136.
        /// <para>
        /// 1st Home Team Odd/Even
        /// </para>
        /// </summary>
        public const int First_Home_Team_OddEven = 136;

        /// <summary>
        /// BetType = 137.
        /// <para>
        /// Home Team Odd/Even
        /// </para>
        /// </summary>
        public const int Home_Team_OddEven = 137;

        /// <summary>
        /// BetType = 138.
        /// <para>
        /// 1st Away Team Odd/Even
        /// </para>
        /// </summary>
        public const int First_Away_Team_OddEven = 138;

        /// <summary>
        /// BetType = 139.
        /// <para>
        /// Away Team Odd/Even
        /// </para>
        /// </summary>
        public const int Away_Team_OddEven = 139;

        /// <summary>
        /// BetType = 143.
        /// <para>
        /// First Result/Total Goals
        /// </para>
        /// </summary>
        public const int First_Result_Total_Goals = 143;

        /// <summary>
        /// BetType = 144.
        /// <para>
        /// Result/Total Goals
        /// </para>
        /// </summary>
        public const int Result_Total_Goals = 144;

        /// <summary>
        /// Set x Winner.
        /// </summary>
        public const int Set_X_Winner = 154;

        /// <summary>
        /// Set x Game Handicap.
        /// </summary>
        public const int Set_X_Game_Handicap = 155;

        /// <summary>
        /// Set X Total Game.
        /// </summary>
        public const int Set_X_Total_Games = 156;

        /// <summary>
        /// BetType = 1000.
        /// </summary>
        public const int P2P = 1000;

        /// <summary>
        /// BetType = 81.
        /// </summary>
        public const int _1st_Ball_OU = 81;

        /// <summary>
        /// BetType = 82.
        /// </summary>
        public const int Last_Ball_OU = 82;

        /// <summary>
        /// BetType = 83.
        /// </summary>
        public const int _1st_Ball_OE = 83;

        /// <summary>
        /// BetType = 84.
        /// </summary>
        public const int Last_Ball_OE = 84;

        /// <summary>
        /// BetType = 85.
        /// </summary>
        public const int N_Over_Under = 85;

        /// <summary>
        /// BetType = 86.
        /// </summary>
        public const int N_Odd_Even = 86;

        /// <summary>
        /// BetType = 87.
        /// </summary>
        public const int Next_High_Low = 87;

        /// <summary>
        /// BetType = 88.
        /// </summary>
        public const int Warrior = 88;

        /// <summary>
        /// BetType = 89.
        /// </summary>
        public const int Next_Combo = 89;

        /// <summary>
        /// BetType = 90.
        /// </summary>
        public const int NumberWheel = 90;

        /// <summary>
        /// BetType = 1101.
        /// </summary>
        public const int Baccarat = 1101;

        /// <summary>
        /// BetType = 1102.
        /// </summary>
        public const int Roulette = 1102;

        /// <summary>
        /// BetType = 1103.
        /// </summary>
        public const int Sicbo = 1103;

        /// <summary>
        /// BetType = 1104.
        /// </summary>
        public const int LiveCasino_LiveRoulette = 1104;

        /// <summary>
        /// BetType = 1201.
        /// </summary>
        public const int VS_Handicap = 1201;

        /// <summary>
        /// BetType = 1203.
        /// </summary>
        public const int VS_OverUnder = 1203;

        /// <summary>
        /// BetType = 1204.
        /// </summary>
        public const int VS_CorrectScore = 1204;

        /// <summary>
        /// BetType = 1205.
        /// </summary>
        public const int VS_1X2 = 1205;

        /// <summary>
        /// BetType = 1206.
        /// </summary>
        public const int VS_TotalGoal = 1206;

        /// <summary>
        /// BetType = 1224.
        /// </summary>
        public const int VS_DoubleChange = 1224;

        /// <summary>
        /// BetType = 1231.
        /// </summary>
        public const int VHR_Win = 1231;

        /// <summary>
        /// BetType = 1232.
        /// </summary>
        public const int VHR_Place = 1232;

        /// <summary>
        /// BetType = 1233.
        /// </summary>
        public const int VHR_WinPlace = 1233;

        /// <summary>
        /// BetType = 1237.
        /// </summary>
        public const int VHR_Forecast = 1237;

        /// <summary>
        /// BetType = 1238.
        /// </summary>
        public const int VHR_Tricast = 1238;

        /// <summary>
        /// BetType = 1220.
        /// </summary>
        public const int VT_PlayerWin = 1220;

        /// <summary>
        /// BetType = 1235.
        /// </summary>
        public const int VT_ScoreBet = 1235;

        /// <summary>
        /// BetType = 1236.
        /// </summary>
        public const int VT_TotalPoints = 1236;

        /// <summary>
        /// BetType = 1301.
        /// </summary>
        public const int MatchWinner = 1301;

        /// <summary>
        /// BetType = 1302.
        /// </summary>
        public const int MatchCorrectScore = 1302;

        /// <summary>
        /// BetType = 1303.
        /// </summary>
        public const int SetHandicap = 1303;

        /// <summary>
        /// BetType = 1304.
        /// </summary>
        public const int TotalSets = 1304;

        /// <summary>
        /// BetType = 1305.
        /// </summary>
        public const int MatchTotalGamesOddEven = 1305;

        /// <summary>
        /// BetType = 1306.
        /// </summary>
        public const int MatchTotalGamesOverUnder = 1306;

        /// <summary>
        /// BetType = 1307.
        /// </summary>
        public const int MatchTotalGames3Way = 1307;

        /// <summary>
        /// BetType = 1308.
        /// </summary>
        public const int GameHandicap3rd = 1308;

        /// <summary>
        /// BetType = 1309.
        /// </summary>
        public const int MatchHandicapGames3Way = 1309;

        /// <summary>
        /// BetType = 1310.
        /// </summary>
        public const int PlayerXMatchTotalGames2Way = 1310;

        /// <summary>
        /// BetType = 1311.
        /// </summary>
        public const int SetXWinner = 1311;

        /// <summary>
        /// BetType = 1312.
        /// </summary>
        public const int SetXTotalGames2Way = 1312;

        /// <summary>
        /// BetType = 1313.
        /// </summary>
        public const int SetXTotalGames3Way = 1313;

        /// <summary>
        /// BetType = 1314.
        /// </summary>
        public const int SetXWillThereBeATiebreak = 1314;

        /// <summary>
        /// BetType = 1315.
        /// </summary>
        public const int SetXPlayerToWinOnATiebreak = 1315;

        /// <summary>
        /// BetType = 1316.
        /// </summary>
        public const int SetXGameHandicap = 1316;

        /// <summary>
        /// BetType = 1317.
        /// </summary>
        public const int SetXCorrectScore = 1317;

        /// <summary>
        /// BetType = 1318.
        /// </summary>
        public const int SetXTotalGamesOddEven = 1318;

        /// <summary>
        /// BetType = 1319.
        /// </summary>
        public const int SetXRaceToYGames = 1319;

        /// <summary>
        /// BetType = 1320.
        /// </summary>
        public const int SetXScoreAfter2Games = 1320;

        /// <summary>
        /// BetType = 1321.
        /// </summary>
        public const int SetXScoreAfter4Games = 1321;

        /// <summary>
        /// BetType = 1322.
        /// </summary>
        public const int SetXScoreAfter6Games = 1322;

        /// <summary>
        /// BetType = 1323.
        /// </summary>
        public const int SetXTotalDeuceGame2Way = 1323;

        /// <summary>
        /// BetType = 1324.
        /// </summary>
        public const int SetXGameYWinner = 1324;

        /// <summary>
        /// BetType = 1325.
        /// </summary>
        public const int SetXGameYCorrectScore = 1325;

        /// <summary>
        /// BetType = 1326.
        /// </summary>
        public const int SetXGameYPointHandicap = 1326;

        /// <summary>
        /// BetType = 1327.
        /// </summary>
        public const int SetXGameYDeuceBetting = 1327;

        /// <summary>
        /// BetType = 1328.
        /// </summary>
        public const int SetXGameYTotalPointsExact = 1328;

        /// <summary>
        /// BetType = 1329.
        /// </summary>
        public const int SetXGameYTotalPoints2Way = 1329;

        /// <summary>
        /// BetType = 1330.
        /// </summary>
        public const int SetXGameYTotalPoints3Way = 1330;

        /// <summary>
        /// BetType = 1331.
        /// </summary>
        public const int SetXGameYTotalPointsOddEven = 1331;

        /// <summary>
        /// BetType = 1332.
        /// </summary>
        public const int SetXGameYTotalPointZWinner = 1332;

        /// <summary>
        /// BetType = 1333.
        /// </summary>
        public const int SetXGameYAndGameYAdd1Winner = 1333;

        /// <summary>
        /// BetType = 1334.
        /// </summary>
        public const int SetXGameYAndGameYAdd1Points = 1334;

        /// <summary>
        /// BetType = 19001.
        /// </summary>
        public const int Others = 19001;

        /// <summary>
        /// BetType = 30.
        /// </summary>
        public const int FirstCorrectScore = 30;

        /// <summary>
        /// BetType = 1501.
        /// </summary>
        public const int KenoGames = 1501;

        /// <summary>
        /// BetType = 23001.
        /// </summary>
        public const int CasinoTransfer = 23001;

        /// <summary>
        /// BetType = 23002.
        /// </summary>
        public const int CasinoPending = 23002;

        /// <summary>
        /// BetType = 23101.
        /// </summary>
        public const int P2PTransfer = 23101;

        /// <summary>
        /// BetType = 23201.
        /// </summary>
        public const int BingoTransfer = 23201;

        /// <summary>
        /// BetType = 23202.
        /// </summary>
        public const int BingoPending = 23202;

        /// <summary>
        /// PlayTechCasino = 22006.
        /// </summary>
        public const int PlayTechCasino = 22006;

        /// <summary>
        /// HomeToWinBothHalves = 133.
        /// </summary>
        public const int HomeToWinBothHalves = 133;

        /// <summary>
        /// AwayToWinBothHalves = 134.
        /// </summary>
        public const int AwayToWinBothHalves = 134;

        /// <summary>
        /// PenaltyShootoutYesNo = 135.
        /// </summary>
        public const int PenaltyShootoutYesNo = 135;

        /// <summary>
        /// HighestScoringHalf = 140.
        /// </summary>
        public const int HighestScoringHalf = 140;

        /// <summary>
        /// HighestScoringHalfHomeTeam = 141.
        /// </summary>
        public const int HighestScoringHalfHomeTeam = 141;

        /// <summary>
        /// HighestScoringHalfAwayTeam = 142.
        /// </summary>
        public const int HighestScoringHalfAwayTeam = 142;

        /// <summary>
        /// BothTeamsToScore = 145.
        /// </summary>
        public const int BothTeamsToScore = 145;

        /// <summary>
        /// _2ndHalfBothTeamsToScore = 146.
        /// </summary>
        public const int _2ndHalfBothTeamsToScore = 146;

        /// <summary>
        /// HomeToScoreInBothHalves = 147.
        /// </summary>
        public const int HomeToScoreInBothHalves = 147;

        /// <summary>
        /// AwayToScoreInBothHalves = 148.
        /// </summary>
        public const int AwayToScoreInBothHalves = 148;

        /// <summary>
        /// HomeToWinEitherHalf = 149
        /// </summary>
        public const int HomeToWinEitherHalf = 149;

        /// <summary>
        /// AwayToWinEitherHalf = 150.
        /// </summary>
        public const int AwayToWinEitherHalf = 150;

        /// <summary>
        /// _1stHalfDoubleChance = 151.
        /// </summary>
        public const int _1stHalfDoubleChance = 410;

        /// <summary>
        /// _1stHalfDoubleChance = 151.
        /// </summary>
        public const int _3rd1stHalfDoubleChance = 151;

        /// <summary>
        /// HalfTimeFullTimeCorrectScore = 152.
        /// </summary>
        public const int HalfTimeFullTimeCorrectScore = 152;

        /// <summary>
        /// ExactTotalGoals = 406.
        /// </summary>
        public const int ExactTotalGoals = 406;

        /// <summary>
        /// 3rd ExactTotalGoals = 159.
        /// </summary>
        public const int _3rdExactTotalGoals = 159;

        /// <summary>
        /// Exact Home Team Goals = 407.
        /// </summary>
        public const int ExactHomeTeamGoals = 407;

        /// <summary>
        /// 3rd Exact Home Team Goals = 161.
        /// </summary>
        public const int _3rdExactHomeTeamGoals = 161;

        /// <summary>
        /// Winning Margin = 408.
        /// </summary>
        public const int WinningMargin = 408;

        /// <summary>
        /// 3rd Winning Margin = 161.
        /// </summary>
        public const int _3rdWinningMargin = 171;

        /// <summary>
        /// 1H Draw No Bet = 411.
        /// </summary>
        public const int _1HDrawNoBet = 411;

        /// <summary>
        /// 3rd 1H Draw No Bet = 191.
        /// </summary>
        public const int _3rd1HDrawNoBet = 191;

        /// <summary>
        /// 2H Correct Score, Bet type ID = 405
        /// </summary>
        public const int _2HCorrectScore = 405;
    }
}