// <auto-generated/>
namespace Fanex.BetList.Core.UnitTest.Builder.OddsBuilder
{
    using Common;
    using Common.Enums;
    using Core.Builder.OddsBuilder;
    using Entities;
    using NUnit.Framework;
    using Stubs;

    public class Odds33Test
    {
        private Odds33 _odds;
        private ITicket _ticket;
        private ITicketHelper _ticketHelperStub;

        [SetUp]
        public void Setup()
        {
            _odds = new Odds33();
            _ticket = TestData.CreateTicket(BetTypes.Win_Place);
            _ticketHelperStub = new TicketHelperStub();
        }
    }
}