// <auto-generated/>
using System.Web.Mvc;

namespace Fanex.BetList.Example.MVC
{
    public class FilterConfig
    {
        public static void RegisterGlobalFilters(GlobalFilterCollection filters)
        {
            filters.Add(new HandleErrorAttribute());
        }
    }
}