// <auto-generated/>
using System.Web.Mvc;
using System.Web.Routing;

namespace Fanex.BetList.Example.MVC
{
    public class RouteConfig
    {
        public static void RegisterRoutes(RouteCollection routes)
        {
            routes.IgnoreRoute("{resource}.axd/{*pathInfo}");

            routes.MapRoute(
                name: "Default",
                url: "{controller}/{action}/{id}",
                defaults: new
                {
                    controller = "BetList",
                    action = "All",
                    id = UrlParameter.Optional
                }
            );
        }
    }
}