// <auto-generated/>
namespace Fanex.BetList.Core.UnitTest.Builder.ChoiceBuilder
{
    using System;
    using Common.Enums;
    using Core.Builder.ChoiceBuilder;
    using Entities;
    using NSubstitute;
    using NUnit.Framework;

    /// <summary>
    /// Unit test for Choice29 class.
    /// </summary>
    [TestFixture]
    public class Choice29Test
    {
        private IChoice _choice;
        private ITicket _ticket;
        private ITicketHelper _ticketHelper;

        [SetUp]
        public void Setup()
        {
            _choice = new Choice29();
            _ticket = Substitute.For<ITicket>();
            _ticket.BetTypeId = BetTypes.Combine_Mix_Parlay;
            _ticketHelper = Substitute.For<ITicketHelper>();
        }

        /// <summary>
        /// The value of Template.BetType.betTypeName is always bet type name.
        /// </summary>
        [Test]
        public void BuildChoice_ClientDetailSystemParlayFunctionIsEmptyAndClientSystemParlaySubbetsDetailFunctionIsEmptyAndShowSystemParlayDetailIsFalse_ReturnTemplate()
        {
            // Arrange
            _ticketHelper.Index = 1;
            _ticketHelper.ClientDetailSystemParlayFunction = string.Empty;
            _ticketHelper.ClientSystemParlaySubbetsDetailFunction = string.Empty;
            _ticketHelper.ShowSystemParlayDetail = false;
            _ticket.RefNo = "300";
            _ticket.WinlostDate = new DateTime(2014, 01, 01, 12, 00, 00);
            _ticket.BetId = 100;
            _ticket.CustId = 10000;
            _ticket.TransId = 200;

            // Act
            _choice.Render(_ticket, _ticketHelper, null, Arg.Any<bool>());

            // Assert
            string expected = "<div class=\"combinationLink\"><a id=\"hidden0\" href=\"javascript:showCombMP(&quot;200&quot;,&quot;1&quot;,&quot;300&quot;);\"></a> - <span style=\"color:#3a3a3a\"></span></div><div id=\"divEvent_2001\" style=\"display: none\" ></div>";
            Assert.AreEqual(expected, _choice.Template.ToString());
        }

        /// <summary>
        /// The value of Template.BetType.betTypeName is always bet type name.
        /// </summary>
        [Test]
        public void BuildChoice_ClientDetailSystemParlayFunctionIsEmptyAndClientSystemParlaySubbetsDetailFunctionIsEmptyAndShowSystemParlayDetailIsTrue_ReturnTemplate()
        {
            // Arrange
            _ticketHelper.Index = 1;
            _ticketHelper.ClientDetailSystemParlayFunction = string.Empty;
            _ticketHelper.ClientSystemParlaySubbetsDetailFunction = string.Empty;
            _ticketHelper.ShowSystemParlayDetail = true;
            _ticket.RefNo = "300";
            _ticket.WinlostDate = new DateTime(2014, 01, 01, 12, 00, 00);
            _ticket.BetId = 100;
            _ticket.CustId = 10000;
            _ticket.TransId = 200;

            // Act
            _choice.Render(_ticket, _ticketHelper, null, Arg.Any<bool>());

            // Assert
            string expected = "<div class=\"combinationLink\"><a id=\"hidden0\" href=\"javascript:showCombMP(&quot;200&quot;,&quot;1&quot;,&quot;300&quot;);\"></a> - <span style=\"color:#3a3a3a\"></span></div><div id=\"divEvent_2001\" style=\"display: none\" ></div><div class=\"detail\" onclick='showCombMPDetail(&quot;300&quot;,&quot;1/1/2014 12:00:00 PM&quot;,&quot;200&quot;,&quot;100&quot;,&quot;10000&quot;);'><a style=\"color:#755200;font-weight:bold\" href=\"javascript:void(&quot;&quot;);\">Details</a></div>";
            Assert.AreEqual(expected, _choice.Template.ToString());
        }
    }
}