//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fanex.BetList.Core.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CoreBetList {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoreBetList() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fanex.BetList.Core.App_GlobalResources.CoreBetList", typeof(CoreBetList).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        public static string a {
            get {
                return ResourceManager.GetString("a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AD.
        /// </summary>
        public static string ad {
            get {
                return ResourceManager.GetString("ad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AH.
        /// </summary>
        public static string ah {
            get {
                return ResourceManager.GetString("ah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AM.
        /// </summary>
        public static string AM {
            get {
                return ResourceManager.GetString("AM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string amount {
            get {
                return ResourceManager.GetString("amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        public static string and {
            get {
                return ResourceManager.GetString("and", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AOS.
        /// </summary>
        public static string AOS {
            get {
                return ResourceManager.GetString("AOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at.
        /// </summary>
        public static string at {
            get {
                return ResourceManager.GetString("at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Away FG.
        /// </summary>
        public static string AwayFG {
            get {
                return ResourceManager.GetString("AwayFG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Away LG.
        /// </summary>
        public static string AwayLG {
            get {
                return ResourceManager.GetString("AwayLG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Away To Win Any Other Score.
        /// </summary>
        public static string AwayToWinAnyOtherScore {
            get {
                return ResourceManager.GetString("AwayToWinAnyOtherScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bets.
        /// </summary>
        public static string bet {
            get {
                return ResourceManager.GetString("bet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bet List.
        /// </summary>
        public static string BetList {
            get {
                return ResourceManager.GetString("BetList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bet Type.
        /// </summary>
        public static string bettype {
            get {
                return ResourceManager.GetString("bettype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Between {0} and {1}.
        /// </summary>
        public static string betweenXandY {
            get {
                return ResourceManager.GetString("betweenXandY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bingo.
        /// </summary>
        public static string bingo {
            get {
                return ResourceManager.GetString("bingo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bought.
        /// </summary>
        public static string Bought {
            get {
                return ResourceManager.GetString("Bought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casino.
        /// </summary>
        public static string casino {
            get {
                return ResourceManager.GetString("casino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casino Games.
        /// </summary>
        public static string casinoGame {
            get {
                return ResourceManager.GetString("casinoGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casino Progressive Bonus.
        /// </summary>
        public static string casinoProgressiveBonus {
            get {
                return ResourceManager.GetString("casinoProgressiveBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choice.
        /// </summary>
        public static string choice {
            get {
                return ResourceManager.GetString("choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comm.
        /// </summary>
        public static string com {
            get {
                return ResourceManager.GetString("com", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combination.
        /// </summary>
        public static string combination {
            get {
                return ResourceManager.GetString("combination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commission.
        /// </summary>
        public static string commission {
            get {
                return ResourceManager.GetString("commission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string content {
            get {
                return ResourceManager.GetString("content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corners.
        /// </summary>
        public static string Corners {
            get {
                return ResourceManager.GetString("Corners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string customer {
            get {
                return ResourceManager.GetString("customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D.
        /// </summary>
        public static string d {
            get {
                return ResourceManager.GetString("d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DA.
        /// </summary>
        public static string da {
            get {
                return ResourceManager.GetString("da", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DD.
        /// </summary>
        public static string dd {
            get {
                return ResourceManager.GetString("dd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dec.
        /// </summary>
        public static string dec {
            get {
                return ResourceManager.GetString("dec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string details {
            get {
                return ResourceManager.GetString("details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw.
        /// </summary>
        public static string draw {
            get {
                return ResourceManager.GetString("draw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Even/Even.
        /// </summary>
        public static string ee {
            get {
                return ResourceManager.GetString("ee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string enable {
            get {
                return ResourceManager.GetString("enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Even/Odd.
        /// </summary>
        public static string eo {
            get {
                return ResourceManager.GetString("eo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Even.
        /// </summary>
        public static string even {
            get {
                return ResourceManager.GetString("even", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        public static string events {
            get {
                return ResourceManager.GetString("events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exactly.
        /// </summary>
        public static string exactly {
            get {
                return ResourceManager.GetString("exactly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluding.
        /// </summary>
        public static string Excluding {
            get {
                return ResourceManager.GetString("Excluding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Time.
        /// </summary>
        public static string ExtraTime {
            get {
                return ResourceManager.GetString("ExtraTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Time HT.1.
        /// </summary>
        public static string ExtraTimeHTDotOne {
            get {
                return ResourceManager.GetString("ExtraTimeHTDotOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Time HT.2.
        /// </summary>
        public static string ExtraTimeHTDotTwo {
            get {
                return ResourceManager.GetString("ExtraTimeHTDotTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Time HT.X.
        /// </summary>
        public static string ExtraTimeHTDotX {
            get {
                return ResourceManager.GetString("ExtraTimeHTDotX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FG/LG.
        /// </summary>
        public static string fglg {
            get {
                return ResourceManager.GetString("fglg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        public static string first {
            get {
                return ResourceManager.GetString("first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Half.
        /// </summary>
        public static string FirstHalf {
            get {
                return ResourceManager.GetString("FirstHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5&amp;Over.
        /// </summary>
        public static string FiveAndOver {
            get {
                return ResourceManager.GetString("FiveAndOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 Goals.
        /// </summary>
        public static string FiveGoals {
            get {
                return ResourceManager.GetString("FiveGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4&amp;Over.
        /// </summary>
        public static string FourAndOver {
            get {
                return ResourceManager.GetString("FourAndOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4&amp;Over Corners.
        /// </summary>
        public static string FourAndOverCorners {
            get {
                return ResourceManager.GetString("FourAndOverCorners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 Goals.
        /// </summary>
        public static string FourGoals {
            get {
                return ResourceManager.GetString("FourGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 Goals &amp;Over.
        /// </summary>
        public static string FourGoalsAndOver {
            get {
                return ResourceManager.GetString("FourGoalsAndOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string from {
            get {
                return ResourceManager.GetString("from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FT.
        /// </summary>
        public static string ft {
            get {
                return ResourceManager.GetString("ft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        public static string game {
            get {
                return ResourceManager.GetString("game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        public static string games {
            get {
                return ResourceManager.GetString("games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        public static string go {
            get {
                return ResourceManager.GetString("go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H.
        /// </summary>
        public static string h {
            get {
                return ResourceManager.GetString("h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HA.
        /// </summary>
        public static string ha {
            get {
                return ResourceManager.GetString("ha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HD.
        /// </summary>
        public static string hd {
            get {
                return ResourceManager.GetString("hd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hdp.
        /// </summary>
        public static string hdp {
            get {
                return ResourceManager.GetString("hdp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HH.
        /// </summary>
        public static string hh {
            get {
                return ResourceManager.GetString("hh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string high {
            get {
                return ResourceManager.GetString("high", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home FG.
        /// </summary>
        public static string HomeFG {
            get {
                return ResourceManager.GetString("HomeFG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home LG.
        /// </summary>
        public static string HomeLG {
            get {
                return ResourceManager.GetString("HomeLG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home To Win Any Other Score.
        /// </summary>
        public static string HomeToWinAnyOtherScore {
            get {
                return ResourceManager.GetString("HomeToWinAnyOtherScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Racing.
        /// </summary>
        public static string Horse {
            get {
                return ResourceManager.GetString("Horse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Racing.
        /// </summary>
        public static string hr {
            get {
                return ResourceManager.GetString("hr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HT.
        /// </summary>
        public static string ht {
            get {
                return ResourceManager.GetString("ht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal.
        /// </summary>
        public static string Internal {
            get {
                return ResourceManager.GetString("Internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP.
        /// </summary>
        public static string ip {
            get {
                return ResourceManager.GetString("ip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        public static string last {
            get {
                return ResourceManager.GetString("last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both.
        /// </summary>
        public static string lblBoth {
            get {
                return ResourceManager.GetString("lblBoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw.
        /// </summary>
        public static string lblDraw {
            get {
                return ResourceManager.GetString("lblDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lose.
        /// </summary>
        public static string lblLose {
            get {
                return ResourceManager.GetString("lblLose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M = Master.
        /// </summary>
        public static string lblM {
            get {
                return ResourceManager.GetString("lblM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mix Parlay.
        /// </summary>
        public static string lblMixParlay {
            get {
                return ResourceManager.GetString("lblMixParlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neither.
        /// </summary>
        public static string lblNeither {
            get {
                return ResourceManager.GetString("lblNeither", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string lblNo {
            get {
                return ResourceManager.GetString("lblNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Draw.
        /// </summary>
        public static string lblNoDraw {
            get {
                return ResourceManager.GetString("lblNoDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One.
        /// </summary>
        public static string lblOne {
            get {
                return ResourceManager.GetString("lblOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        public static string lblOr {
            get {
                return ResourceManager.GetString("lblOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over/Even.
        /// </summary>
        public static string lblOverEven {
            get {
                return ResourceManager.GetString("lblOverEven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over/Odd.
        /// </summary>
        public static string lblOverOdd {
            get {
                return ResourceManager.GetString("lblOverOdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        public static string lblRunning {
            get {
                return ResourceManager.GetString("lblRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S = Super.
        /// </summary>
        public static string lblS {
            get {
                return ResourceManager.GetString("lblS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Parlay.
        /// </summary>
        public static string lblSystemParlay {
            get {
                return ResourceManager.GetString("lblSystemParlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under/Even.
        /// </summary>
        public static string lblUnderEven {
            get {
                return ResourceManager.GetString("lblUnderEven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under/Odd.
        /// </summary>
        public static string lblUnderOdd {
            get {
                return ResourceManager.GetString("lblUnderOdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting.
        /// </summary>
        public static string lblWaiting {
            get {
                return ResourceManager.GetString("lblWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Won.
        /// </summary>
        public static string lblWon {
            get {
                return ResourceManager.GetString("lblWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string lblYes {
            get {
                return ResourceManager.GetString("lblYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to League.
        /// </summary>
        public static string league {
            get {
                return ResourceManager.GetString("league", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Baccarat.
        /// </summary>
        public static string LiveBaccarat {
            get {
                return ResourceManager.GetString("LiveBaccarat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Casino.
        /// </summary>
        public static string LiveCasino {
            get {
                return ResourceManager.GetString("LiveCasino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Roulette.
        /// </summary>
        public static string LiveRoulette {
            get {
                return ResourceManager.GetString("LiveRoulette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lose.
        /// </summary>
        public static string lose {
            get {
                return ResourceManager.GetString("lose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total of losing tickets.
        /// </summary>
        public static string losingtickets {
            get {
                return ResourceManager.GetString("losingtickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string low {
            get {
                return ResourceManager.GetString("low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mar.
        /// </summary>
        public static string mar {
            get {
                return ResourceManager.GetString("mar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match.
        /// </summary>
        public static string match {
            get {
                return ResourceManager.GetString("match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member.
        /// </summary>
        public static string member {
            get {
                return ResourceManager.GetString("member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        public static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mon.
        /// </summary>
        public static string mon {
            get {
                return ResourceManager.GetString("mon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (N).
        /// </summary>
        public static string Neutral {
            get {
                return ResourceManager.GetString("Neutral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string next {
            get {
                return ResourceManager.GetString("next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        public static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Goal.
        /// </summary>
        public static string nogoal {
            get {
                return ResourceManager.GetString("nogoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Goal.
        /// </summary>
        public static string NoGoalBetType14 {
            get {
                return ResourceManager.GetString("NoGoalBetType14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Goals.
        /// </summary>
        public static string NoGoals {
            get {
                return ResourceManager.GetString("NoGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string none {
            get {
                return ResourceManager.GetString("none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string normal {
            get {
                return ResourceManager.GetString("normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Tiebreak.
        /// </summary>
        public static string noTiebreak {
            get {
                return ResourceManager.GetString("noTiebreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Game.
        /// </summary>
        public static string numbergame {
            get {
                return ResourceManager.GetString("numbergame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Game No.
        /// </summary>
        public static string numbergameno {
            get {
                return ResourceManager.GetString("numbergameno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Wheel.
        /// </summary>
        public static string numberGroup {
            get {
                return ResourceManager.GetString("numberGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odd.
        /// </summary>
        public static string odd {
            get {
                return ResourceManager.GetString("odd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odds.
        /// </summary>
        public static string odds {
            get {
                return ResourceManager.GetString("odds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odd/Even.
        /// </summary>
        public static string oe {
            get {
                return ResourceManager.GetString("oe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string of {
            get {
                return ResourceManager.GetString("of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Goal.
        /// </summary>
        public static string OneGoal {
            get {
                return ResourceManager.GetString("OneGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odd/Odd.
        /// </summary>
        public static string oo {
            get {
                return ResourceManager.GetString("oo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string open {
            get {
                return ResourceManager.GetString("open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OT.
        /// </summary>
        public static string OT {
            get {
                return ResourceManager.GetString("OT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string other {
            get {
                return ResourceManager.GetString("other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outstanding.
        /// </summary>
        public static string outstanding {
            get {
                return ResourceManager.GetString("outstanding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over.
        /// </summary>
        public static string over {
            get {
                return ResourceManager.GetString("over", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2P.
        /// </summary>
        public static string P2 {
            get {
                return ResourceManager.GetString("P2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P2P.
        /// </summary>
        public static string P2P {
            get {
                return ResourceManager.GetString("P2P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poker Games.
        /// </summary>
        public static string p2pGame {
            get {
                return ResourceManager.GetString("p2pGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parlay.
        /// </summary>
        public static string parlay {
            get {
                return ResourceManager.GetString("parlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party Baccarat.
        /// </summary>
        public static string PartyBaccarat {
            get {
                return ResourceManager.GetString("PartyBaccarat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party Roulette.
        /// </summary>
        public static string PartyRoulette {
            get {
                return ResourceManager.GetString("PartyRoulette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Penalty.
        /// </summary>
        public static string Penalty {
            get {
                return ResourceManager.GetString("Penalty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string pending {
            get {
                return ResourceManager.GetString("pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place.
        /// </summary>
        public static string place {
            get {
                return ResourceManager.GetString("place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        public static string player {
            get {
                return ResourceManager.GetString("player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlayTech Casino.
        /// </summary>
        public static string playtechcasino {
            get {
                return ResourceManager.GetString("playtechcasino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        public static string points {
            get {
                return ResourceManager.GetString("points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string product {
            get {
                return ResourceManager.GetString("product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PT.
        /// </summary>
        public static string pt {
            get {
                return ResourceManager.GetString("pt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race.
        /// </summary>
        public static string race {
            get {
                return ResourceManager.GetString("race", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ref No.
        /// </summary>
        public static string refno {
            get {
                return ResourceManager.GetString("refno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund.
        /// </summary>
        public static string refund {
            get {
                return ResourceManager.GetString("refund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular Time.
        /// </summary>
        public static string RegularTime {
            get {
                return ResourceManager.GetString("RegularTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string reject {
            get {
                return ResourceManager.GetString("reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string reset {
            get {
                return ResourceManager.GetString("reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string result {
            get {
                return ResourceManager.GetString("result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string results {
            get {
                return ResourceManager.GetString("results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roulette.
        /// </summary>
        public static string Roulette {
            get {
                return ResourceManager.GetString("Roulette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        public static string running {
            get {
                return ResourceManager.GetString("running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SB.
        /// </summary>
        public static string SB {
            get {
                return ResourceManager.GetString("SB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCR.
        /// </summary>
        public static string scr {
            get {
                return ResourceManager.GetString("scr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.Draw.
        /// </summary>
        public static string SDraw {
            get {
                return ResourceManager.GetString("SDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  sec.
        /// </summary>
        public static string sec {
            get {
                return ResourceManager.GetString("sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Half.
        /// </summary>
        public static string SecondHalf {
            get {
                return ResourceManager.GetString("SecondHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        public static string set {
            get {
                return ResourceManager.GetString("set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string setting {
            get {
                return ResourceManager.GetString("setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7&amp;Over.
        /// </summary>
        public static string SevenAndOver {
            get {
                return ResourceManager.GetString("SevenAndOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7&amp;Over Corners.
        /// </summary>
        public static string SevenAndOverCorners {
            get {
                return ResourceManager.GetString("SevenAndOverCorners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6&amp;Over.
        /// </summary>
        public static string SixAndOver {
            get {
                return ResourceManager.GetString("SixAndOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 Goals.
        /// </summary>
        public static string SixGoals {
            get {
                return ResourceManager.GetString("SixGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sold.
        /// </summary>
        public static string Sold {
            get {
                return ResourceManager.GetString("Sold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sport.
        /// </summary>
        public static string sport {
            get {
                return ResourceManager.GetString("sport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stake.
        /// </summary>
        public static string stake {
            get {
                return ResourceManager.GetString("stake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Total.
        /// </summary>
        public static string subTotal {
            get {
                return ResourceManager.GetString("subTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string summary {
            get {
                return ResourceManager.GetString("summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        public static string table {
            get {
                return ResourceManager.GetString("table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tennis.
        /// </summary>
        public static string Tennis {
            get {
                return ResourceManager.GetString("Tennis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TF.
        /// </summary>
        public static string tf {
            get {
                return ResourceManager.GetString("tf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no ticket detail available..
        /// </summary>
        public static string ThereIsNoTicketDetailAvailable {
            get {
                return ResourceManager.GetString("ThereIsNoTicketDetailAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3&amp;Over.
        /// </summary>
        public static string ThreeAndOver {
            get {
                return ResourceManager.GetString("ThreeAndOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 Goals.
        /// </summary>
        public static string ThreeGoals {
            get {
                return ResourceManager.GetString("ThreeGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 Goals &amp;Over.
        /// </summary>
        public static string ThreeGoalsAndOver {
            get {
                return ResourceManager.GetString("ThreeGoalsAndOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tie.
        /// </summary>
        public static string Tie {
            get {
                return ResourceManager.GetString("Tie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string time {
            get {
                return ResourceManager.GetString("time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string to {
            get {
                return ResourceManager.GetString("to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string total {
            get {
                return ResourceManager.GetString("total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to Win by 1 Goal.
        /// </summary>
        public static string ToWinByOneGoal {
            get {
                return ResourceManager.GetString("ToWinByOneGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to Win by 3up Goals.
        /// </summary>
        public static string ToWinByThreeUpGoals {
            get {
                return ResourceManager.GetString("ToWinByThreeUpGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to Win by 2 Goals.
        /// </summary>
        public static string ToWinByTwoGoals {
            get {
                return ResourceManager.GetString("ToWinByTwoGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        public static string transfer {
            get {
                return ResourceManager.GetString("transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12&amp;Over Corners.
        /// </summary>
        public static string TwelveAndOverCorners {
            get {
                return ResourceManager.GetString("TwelveAndOverCorners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 Goals.
        /// </summary>
        public static string TwoGoals {
            get {
                return ResourceManager.GetString("TwoGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 Goals &amp;Over.
        /// </summary>
        public static string TwoGoalsAndOver {
            get {
                return ResourceManager.GetString("TwoGoalsAndOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2H.1.
        /// </summary>
        public static string TwoHDotOne {
            get {
                return ResourceManager.GetString("TwoHDotOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2H.2.
        /// </summary>
        public static string TwoHDotTwo {
            get {
                return ResourceManager.GetString("TwoHDotTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2H.X.
        /// </summary>
        public static string TwoHDotX {
            get {
                return ResourceManager.GetString("TwoHDotX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under.
        /// </summary>
        public static string under {
            get {
                return ResourceManager.GetString("under", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UP.
        /// </summary>
        public static string Up {
            get {
                return ResourceManager.GetString("Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update All.
        /// </summary>
        public static string UpdateAll {
            get {
                return ResourceManager.GetString("UpdateAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UP points.
        /// </summary>
        public static string upPoints {
            get {
                return ResourceManager.GetString("upPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string view {
            get {
                return ResourceManager.GetString("view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0-Win.
        /// </summary>
        public static string virtualtennis_scorebet_0_win {
            get {
                return ResourceManager.GetString("virtualtennis_scorebet_0_win", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15-Win.
        /// </summary>
        public static string virtualtennis_scorebet_15_win {
            get {
                return ResourceManager.GetString("virtualtennis_scorebet_15_win", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30-Win.
        /// </summary>
        public static string virtualtennis_scorebet_30_win {
            get {
                return ResourceManager.GetString("virtualtennis_scorebet_30_win", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40-Win.
        /// </summary>
        public static string virtualtennis_scorebet_40_win {
            get {
                return ResourceManager.GetString("virtualtennis_scorebet_40_win", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win-0.
        /// </summary>
        public static string virtualtennis_scorebet_win_0 {
            get {
                return ResourceManager.GetString("virtualtennis_scorebet_win_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win-15.
        /// </summary>
        public static string virtualtennis_scorebet_win_15 {
            get {
                return ResourceManager.GetString("virtualtennis_scorebet_win_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win-30.
        /// </summary>
        public static string virtualtennis_scorebet_win_30 {
            get {
                return ResourceManager.GetString("virtualtennis_scorebet_win_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win-40.
        /// </summary>
        public static string virtualtennis_scorebet_win_40 {
            get {
                return ResourceManager.GetString("virtualtennis_scorebet_win_40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Void.
        /// </summary>
        public static string voided {
            get {
                return ResourceManager.GetString("voided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting.
        /// </summary>
        public static string waiting {
            get {
                return ResourceManager.GetString("waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warrior.
        /// </summary>
        public static string warrior {
            get {
                return ResourceManager.GetString("warrior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2nd ball win.
        /// </summary>
        public static string warrior2ndBall {
            get {
                return ResourceManager.GetString("warrior2ndBall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3rd ball win.
        /// </summary>
        public static string warrior3rdBall {
            get {
                return ResourceManager.GetString("warrior3rdBall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wed.
        /// </summary>
        public static string wed {
            get {
                return ResourceManager.GetString("wed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win.
        /// </summary>
        public static string win {
            get {
                return ResourceManager.GetString("win", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win Loss.
        /// </summary>
        public static string winloss {
            get {
                return ResourceManager.GetString("winloss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Won.
        /// </summary>
        public static string won {
            get {
                return ResourceManager.GetString("won", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 Goals.
        /// </summary>
        public static string ZeroGoals {
            get {
                return ResourceManager.GetString("ZeroGoals", resourceCulture);
            }
        }
    }
}
