// <auto-generated/>
namespace Fanex.BetList.Core.UnitTest.Builder.StakeBuilder
{
    using Fanex.BetList.Core.Builder.StakeBuilder;
    using Fanex.BetList.Core.Entities;
    using Fanex.BetList.Core.Templates;
    using Fanex.BetList.Core.UnitTest.Common;
    using Fanex.BetList.Core.UnitTest.Common.Enums;
    using NUnit.Framework;

    public class Stake1Test
    {
        private Stake1 _stake;
        private ITicket _ticket;

        [SetUp]
        public void Setup()
        {
            _stake = new Stake1();
            _ticket = TestData.CreateTicket(BetTypes.Handicap);
        }

        [Test]
        public void Ticket_ReturnStakeIsTicketStake()
        {
            // Arrange
            var template = new Stake_Template();

            // Act
            template = _stake.Render(_ticket);

            // Assert
            string expectedTransTime = _ticket.Stake.ToString();
            Assert.AreEqual(expectedTransTime, template.stake);
        }
    }
}