// <auto-generated />
#region!!!This file is auto-generated by TplBuilder, don't modify it manually!!!
using System;
using System.Web;
using System.Text;
using TplCore;
using TplCore.Element;
#pragma warning disable
namespace Fanex.BetList.ColossusBets
{
	using Templates;
	namespace Templates
	{
		public class ColossusBetsDetail_Template : Template
		{
			protected static string s0 = "<div class=\"bet-details-container\"><p class=\"cash-own\">";
			public string cashOwn = "{cashOwn}";
			protected static string s1 = "</p><p class=\"cash-sold\">";
			public string cashSold = "{cashSold}";
			protected static string s2 = "</p><table class=\"bet-details-table\"><thead><tr><th class=\"c\">";
			protected static string s3{get{return Fanex.BetList.Core.App_GlobalResources.CoreBetList.date;}}
			protected static string s4 = "</th><th class=\"c\">";
               protected static string s5 { get { return Fanex.BetList.Core.Resources.ColosussBetsLabel.TransactionType; } }
			protected static string s6 = "</th><th class=\"c\">";
			protected static string s7{get{return Fanex.BetList.Core.App_GlobalResources.CoreBetList.winloss;}}
			protected static string s8 = "</th><th class=\"c\">";
			protected static string s9{get{return Fanex.BetList.Core.App_GlobalResources.CoreBetList.status;}}
			protected static string s10 = "</th></tr></thead><tbody>";
			public ColossusBetsDetail_Contents_Block Contents = new ColossusBetsDetail_Contents_Block();
			public ColossusBetsDetail_NoData_Block NoData = new ColossusBetsDetail_NoData_Block();
			protected static string s11 = "</tbody><tfoot>";
			public ColossusBetsDetail_TotalContents_Block TotalContents = new ColossusBetsDetail_TotalContents_Block();
			protected static string s12 = "</tfoot></table></div>";
			public override void ToString(ref StringBuilder bd)
			{
				if(!Visible) return;
				bd.Append(s0);
				bd.Append(cashOwn);
				bd.Append(s1);
				bd.Append(cashSold);
				bd.Append(s2);
				bd.Append(s3);
				bd.Append(s4);
				bd.Append(s5);
				bd.Append(s6);
				bd.Append(s7);
				bd.Append(s8);
				bd.Append(s9);
				bd.Append(s10);
				if(null != Contents) Contents.ToString(ref bd);
				if(null != NoData) NoData.ToString(ref bd);
				bd.Append(s11);
				if(null != TotalContents) TotalContents.ToString(ref bd);
				bd.Append(s12);
				bd.Append(Value);
			}
			public string ToString()
			{
				StringBuilder bd = new StringBuilder();
				ToString(ref bd);
				return bd.ToString();
			}

		}

		public class ColossusBetsDetail_Contents_Block: Block
		{
			protected static string s13 = "<tr><td class=\"c transaction-date\">";
			public string date = "{date}";
			protected static string s14 = "</td><td class=\"transaction-type\">";
			public string transactionType = "{transactionType}";
			protected static string s15 = "</td><td class=\"r win-loss\">";
			public string winloss = "{winloss}";
			protected static string s16 = "</td><td class=\"c status\">";
			public string status = "{status}";
			protected static string s17 = "</td></tr>";
			public override void ToString(ref StringBuilder bd)
			{
				if(!Visible) return;
				if(RenderChild)
				{
					bd.Append(s13);
					bd.Append(date);
					bd.Append(s14);
					bd.Append(transactionType);
					bd.Append(s15);
					bd.Append(winloss);
					bd.Append(s16);
					bd.Append(status);
					bd.Append(s17);
				}
				if(IsAssigned){bd.Append(Value);}
			}
		}

		public class ColossusBetsDetail_NoData_Block: Block
		{
			protected static string s18 = "<tr><td colspan=\"4\" class=\"c\">";
			protected static string s19{get{return Fanex.BetList.Core.App_GlobalResources.CoreBetList.ThereIsNoTicketDetailAvailable;}}
			protected static string s20 = "</td></tr>";
			public override void ToString(ref StringBuilder bd)
			{
				if(!Visible) return;
				if(RenderChild)
				{
					bd.Append(s18);
					bd.Append(s19);
					bd.Append(s20);
				}
				if(IsAssigned){bd.Append(Value);}
			}
		}

		public class ColossusBetsDetail_TotalContents_Block: Block
		{
			protected static string s21 = "<tr><td colspan=\"2\" class=\"r\">";
			protected static string s22{get{return Fanex.BetList.Core.App_GlobalResources.CoreBetList.total;}}
			protected static string s23 = "</td><td class=\"r\">";
			public string totalWinloss = "{totalWinloss}";
			protected static string s24 = "</td><td></td></tr>";
			public override void ToString(ref StringBuilder bd)
			{
				if(!Visible) return;
				if(RenderChild)
				{
					bd.Append(s21);
					bd.Append(s22);
					bd.Append(s23);
					bd.Append(totalWinloss);
					bd.Append(s24);
				}
				if(IsAssigned){bd.Append(Value);}
			}
		}

	}
}
#pragma warning enable
#endregion