// <auto-generated/>
namespace Fanex.BetList.Keno.Test.Builder.OddsBuilder
{
    using Core.Builder.OddsBuilder;
    using Core.Entities;
    using Core.Templates;
    using Core.UnitTest.Common;
    using Core.UnitTest.Common.Enums;
    using Core.UnitTest.Stubs;
    using NUnit.Framework;

    public class Odds1501Test
    {
        private Odds1501 _odds;
        private ITicket _ticket;
        private ITicketHelper _ticketHelperStub;

        [SetUp]
        public void Setup()
        {
            _odds = new Odds1501();
            _ticket = TestData.CreateTicket(BetTypes.KenoGames);
            _ticketHelperStub = new TicketHelperStub();
        }

        [Test]
        public void OddsTypeIsNull_OddsTypeIsZero()
        {
            // Arrange
            _ticket.OddsType = null;

            // Act
            Odds_Template template = _odds.Render(_ticket, null, null);

            // Assert
            var expectedOdds = "<font color='#B50000'>-0.73</font>";
            Assert.AreEqual(expectedOdds, template.odds);
        }

        [Test]
        public void OddsTypeIsNull_OddsTypeIsZero1()
        {
            // Arrange
            _ticket.OddsType = "1";

            // Act
            Odds_Template template = _odds.Render(_ticket, null, null);

            // Assert
            var expectedOdds = "0.27";
            Assert.AreEqual(expectedOdds, template.odds);
        }

        [Test]
        public void OddsTypeIsNull_OddsTypeIsZero12()
        {
            // Arrange
            _ticket.OddsType = "1";

            // Act
            Odds_Template template = _odds.Render(_ticket, null, null);

            // Assert
            Assert.IsEmpty(template.oddsType);
        }
    }
}