// <auto-generated/>
namespace Fanex.BetList.Core.UnitTest.Utils
{
    using System.Collections.Generic;
    using Fanex.BetList.Core.Utils;
    using NUnit.Framework;

    public class ConvertByBetTypeTest
    {
        private const string FontOpenTag = "<font color='#B50000'>";
        private const string FontCloseTag = "</font>";
        private const string Minus = "<font color='#B50000'>{0}</font>";

        [TestCase(1)]
        [TestCase(2)]
        [TestCase(3)]
        [TestCase(7)]
        [TestCase(8)]
        [TestCase(12)]
        [TestCase(20)]
        [TestCase(21)]
        [TestCase(81)]
        [TestCase(82)]
        [TestCase(83)]
        [TestCase(84)]
        [TestCase(85)]
        [TestCase(86)]
        [TestCase(87)]
        [TestCase(88)]
        [TestCase(124)]
        [TestCase(125)]
        [TestCase(153)]
        [TestCase(154)]
        [TestCase(155)]
        [TestCase(156)]
        [TestCase(157)]
        [TestCase(178)]
        [TestCase(183)]
        [TestCase(184)]
        [TestCase(194)]
        [TestCase(197)]
        [TestCase(198)]
        [TestCase(203)]
        [TestCase(204)]
        [TestCase(205)]
        [TestCase(801)]
        [TestCase(803)]
        [TestCase(804)]
        [TestCase(805)]
        [TestCase(806)]
        [TestCase(1301)]
        [TestCase(1303)]
        [TestCase(1305)]
        [TestCase(1306)]
        [TestCase(1308)]
        [TestCase(1311)]
        [TestCase(1312)]
        [TestCase(1316)]
        [TestCase(1318)]
        [TestCase(1324)]
        public void ShowOddsByBettype_BetTypeIsOddsBetType_ReturnOddsType(int betType)
        {
            // Arrange
            int oddsType = 1;

            // Act
            int result = ConvertByBetType.ShowOddsByBettype(betType, oddsType);

            // Assert
            Assert.AreEqual(oddsType, result);
        }

        [Test]
        public void ShowOddsByBettype_BetTypeIsNotOddsBetType_ReturnZero()
        {
            // Arrange
            int betType = 1000;
            int oddsType = 1;

            // Act
            int result = ConvertByBetType.ShowOddsByBettype(betType, oddsType);

            // Assert
            int expected = 0;
            Assert.AreEqual(expected, result);
        }
    }
}