// <auto-generated />
#region!!!This file is auto-generated by TplBuilder, don't modify it manually!!!
using System;
using System.Web;
using System.Text;
using TplCore;
using TplCore.Element;
#pragma warning disable
namespace Fanex.BetList.Core
{
	using Templates;
	namespace Templates
	{
		public class Odds_Template : Template
		{
			protected static string s0 = "<span class=\"underdog\">";
			public string odds = "{odds}";
			protected static string s1 = "</span><br /><span class=\"oddstype\">";
			public string oddsType = "{oddsType}";
			protected static string s2 = "</span>";
			public override void ToString(ref StringBuilder bd)
			{
				if(!Visible) return;
				if(RenderChild)
				{
					bd.Append(s0);
					bd.Append(odds);
					bd.Append(s1);
					bd.Append(oddsType);
					bd.Append(s2);
				}
				if(IsAssigned){bd.Append(Value);}
			}
			public string ToString()
			{
				StringBuilder bd = new StringBuilder();
				ToString(ref bd);
				return bd.ToString();
			}

		}

	}
}
#pragma warning enable
#endregion