// <auto-generated />
#region!!!This file is auto-generated by TplBuilder, don't modify it manually!!!
using System;
using System.Web;
using System.Text;
using TplCore;
using TplCore.Element;
#pragma warning disable
namespace Fanex.BetList.Core
{
	using Templates;
	namespace Templates
	{
		public class SystemParlayDetail_Template : Template
		{
			protected static string s0 = "<table cellspacing=\"0\" cellpadding=\"0\" border=\"0\" class=\"system-parlay-detail\" style=\"text-align: right;white-space: nowrap; width: 100%; font-weight: bold\"><tr class=\"system-parlay-header\"><th width=\"100\">";
			protected static string s1{get{return App_GlobalResources.CoreBetList.date;}}
			protected static string s2 = "</th><th>";
			protected static string s3{get{return App_GlobalResources.CoreBetList.events;}}
			protected static string s4 = "</th><th width=\"80\">";
			protected static string s5{get{return App_GlobalResources.CoreBetList.odds;}}
			protected static string s6 = "</th><th width=\"80\">";
			protected static string s7{get{return App_GlobalResources.CoreBetList.stake;}}
			protected static string s8 = "</th><th width=\"80\">";
			protected static string s9{get{return App_GlobalResources.CoreBetList.winloss;}}
			protected static string s10 = "</th><th width=\"80\">";
			protected static string s11{get{return App_GlobalResources.CoreBetList.status;}}
			protected static string s12 = "</th></tr>";
			public SystemParlayDetail_Contents_Block Contents = new SystemParlayDetail_Contents_Block();
			public SystemParlayDetail_SubTotalContents_Block SubTotalContents = new SystemParlayDetail_SubTotalContents_Block();
			public SystemParlayDetail_Outstanding_Block Outstanding = new SystemParlayDetail_Outstanding_Block();
			public SystemParlayDetail_TotalContents_Block TotalContents = new SystemParlayDetail_TotalContents_Block();
			protected static string s13 = "</table>";
			public override void ToString(ref StringBuilder bd)
			{
				if(!Visible) return;
				if(RenderChild)
				{
					bd.Append(s0);
					bd.Append(s1);
					bd.Append(s2);
					bd.Append(s3);
					bd.Append(s4);
					bd.Append(s5);
					bd.Append(s6);
					bd.Append(s7);
					bd.Append(s8);
					bd.Append(s9);
					bd.Append(s10);
					bd.Append(s11);
					bd.Append(s12);
					if(null != Contents) Contents.ToString(ref bd);
					if(null != SubTotalContents) SubTotalContents.ToString(ref bd);
					if(null != Outstanding) Outstanding.ToString(ref bd);
					if(null != TotalContents) TotalContents.ToString(ref bd);
					bd.Append(s13);
				}
				if(IsAssigned){bd.Append(Value);}
			}
			public string ToString()
			{
				StringBuilder bd = new StringBuilder();
				ToString(ref bd);
				return bd.ToString();
			}

		}

		public class SystemParlayDetail_Contents_Block: Block
		{
			protected static string s14 = "<tr>";
			public SystemParlayDetail_Contents_WinlossDate_Block WinlossDate = new SystemParlayDetail_Contents_WinlossDate_Block();
			protected static string s15 = "<td style=\"text-align: left; font-weight: normal\">";
			public SystemParlayDetail_Contents_Match_Block Match = new SystemParlayDetail_Contents_Match_Block();
			protected static string s16 = "</td><td>";
			public string Odds = "{Odds}";
			protected static string s17 = "</td><td>";
			public string Stake = "{Stake}";
			protected static string s18 = "</td><td>";
			public string Winloss = "{Winloss}";
			public SystemParlayDetail_Contents_PlayerCommission_Block PlayerCommission = new SystemParlayDetail_Contents_PlayerCommission_Block();
			protected static string s19 = "</td><td style=\"text-align: center;\">";
			public string Status = "{Status}";
			protected static string s20 = "</td></tr>";
			public override void ToString(ref StringBuilder bd)
			{
				if(!Visible) return;
				if(RenderChild)
				{
					bd.Append(s14);
					if(null != WinlossDate) WinlossDate.ToString(ref bd);
					bd.Append(s15);
					if(null != Match) Match.ToString(ref bd);
					bd.Append(s16);
					bd.Append(Odds);
					bd.Append(s17);
					bd.Append(Stake);
					bd.Append(s18);
					bd.Append(Winloss);
					if(null != PlayerCommission) PlayerCommission.ToString(ref bd);
					bd.Append(s19);
					bd.Append(Status);
					bd.Append(s20);
				}
				if(IsAssigned){bd.Append(Value);}
			}
		}

		public class SystemParlayDetail_Contents_WinlossDate_Block: Block
		{
			protected static string s21 = "<td style=\"text-align: center; font-weight: normal\" rowspan=\"";
			public string RowSpan = "{RowSpan}";
			protected static string s22 = "\">";
			public string WinlossDate = "{WinlossDate}";
			protected static string s23 = "</td>";
			public override void ToString(ref StringBuilder bd)
			{
				if(!Visible) return;
				if(RenderChild)
				{
					bd.Append(s21);
					bd.Append(RowSpan);
					bd.Append(s22);
					bd.Append(WinlossDate);
					bd.Append(s23);
				}
				if(IsAssigned){bd.Append(Value);}
			}
		}

		public class SystemParlayDetail_Contents_Match_Block: Block
		{
			protected static string s24 = "<div style=\"padding: 3px 0px\">";
			public string HomeTeam = "{HomeTeam}";
			protected static string s25 = " - vs - ";
			public string AwayTeam = "{AwayTeam}";
			protected static string s26 = "</div>";
			public override void ToString(ref StringBuilder bd)
			{
				if(!Visible) return;
				if(RenderChild)
				{
					bd.Append(s24);
					bd.Append(HomeTeam);
					bd.Append(s25);
					bd.Append(AwayTeam);
					bd.Append(s26);
				}
				if(IsAssigned){bd.Append(Value);}
			}
		}

		public class SystemParlayDetail_Contents_PlayerCommission_Block: Block
		{
			protected static string s27 = "<div class=\"player-commission\">";
			public string PlayerCommission = "{PlayerCommission}";
			protected static string s28 = "</div>";
			public override void ToString(ref StringBuilder bd)
			{
				if(!Visible) return;
				if(RenderChild)
				{
					bd.Append(s27);
					bd.Append(PlayerCommission);
					bd.Append(s28);
				}
				if(IsAssigned){bd.Append(Value);}
			}
		}

		public class SystemParlayDetail_SubTotalContents_Block: Block
		{
			protected static string s29 = "<tr class=\"system-parlay-subtotal\"><td colspan=\"4\">";
			protected static string s30{get{return App_GlobalResources.CoreBetList.subTotal;}}
			protected static string s31 = ":</td><td style=\"border-left: none;\">";
			public string TotalWinloss = "{TotalWinloss}";
			protected static string s32 = "</td><td style=\"border-left: none;\">&nbsp;</td></tr>";
			public override void ToString(ref StringBuilder bd)
			{
				if(!Visible) return;
				if(RenderChild)
				{
					bd.Append(s29);
					bd.Append(s30);
					bd.Append(s31);
					bd.Append(TotalWinloss);
					bd.Append(s32);
				}
				if(IsAssigned){bd.Append(Value);}
			}
		}

		public class SystemParlayDetail_Outstanding_Block: Block
		{
			protected static string s33 = "<tr class=\"system-parlay-outstanding\"><td colspan=\"4\">";
			protected static string s34{get{return App_GlobalResources.CoreBetList.outstanding;}}
			protected static string s35 = ":</td><td style=\"border-left: none;\">";
			public string Outstanding = "{Outstanding}";
			protected static string s36 = "</td><td style=\"border-left: none;\">&nbsp;</td></tr>";
			public override void ToString(ref StringBuilder bd)
			{
				if(!Visible) return;
				if(RenderChild)
				{
					bd.Append(s33);
					bd.Append(s34);
					bd.Append(s35);
					bd.Append(Outstanding);
					bd.Append(s36);
				}
				if(IsAssigned){bd.Append(Value);}
			}
		}

		public class SystemParlayDetail_TotalContents_Block: Block
		{
			protected static string s37 = "<tr class=\"system-parlay-total\"><td colspan=\"4\">";
			protected static string s38{get{return App_GlobalResources.CoreBetList.total;}}
			protected static string s39 = ":</td><td>";
			public string TotalWinloss = "{TotalWinloss}";
			protected static string s40 = "</td><td>&nbsp;</td></tr>";
			public override void ToString(ref StringBuilder bd)
			{
				if(!Visible) return;
				if(RenderChild)
				{
					bd.Append(s37);
					bd.Append(s38);
					bd.Append(s39);
					bd.Append(TotalWinloss);
					bd.Append(s40);
				}
				if(IsAssigned){bd.Append(Value);}
			}
		}

	}
}
#pragma warning enable
#endregion